name: Building and Testing on MacOS üçé

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-gcc:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        build-type: [Release, Debug]

    name: "Build: ${{matrix.os}} ‚Ä¢ ${{matrix.build-type}} ‚Ä¢ Apple Clang"
    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v4

    - name: Configure python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.14.1
      with:
        github-api-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{matrix.build-type}}

    - name: Build C++ Project
      run: cmake --build build --config ${{matrix.build-type}}

    - name: Running C++ Tests
      run: ctest --test-dir build/tests/cpp
