name: ci-windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-msvc:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]
        build-type: [Release, Debug]

    name: "Build: ${{matrix.os}} • ${{matrix.build-type}} • MSVC"
    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v3

    - name: Update CMake
      uses: jwlawson/actions-setup-cmake@v1.14.1
      with:
        github-api-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure CMake
      env:
        CMAKE_GENERATOR: "Visual Studio 17 2022"
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{matrix.build-type}}

    - name: Build C++ Project
      run: cmake --build build --config ${{matrix.build-type}}

    - name: Running C++ Tests
      run: ctest --test-dir build/tests/cpp
